ISSUE: [#277] PURPOSE: data-entry tool. DESCRIPTION: Downgrade to 1.6, since that is compatible with the version of tomcat ubuntu provides. The war file can now at least start, though it immediately hits NoClassDefFoundError: java/nio/file/Paths. Jetty demo still works perfectly.